### ISSUE TITLE
Rename environment variables passed to the container

### ISSUE THREAD

**Issue by sgraband** [eclipsesource/theia-cloud#106]
Currently we prefix all the environment variables we pass into the container with `THEIA_CLOUD`. This however, introduces problems for vscode extensions, as Theia will block all env variables starting with `THEIA_` from being forwarded to vscode extensions (or other processes). Therefore, we should rename out env variables.

**Comment by jfaltermeier** [comment]
Keep open

**Comment by jfaltermeier** [comment]
Fixed with https://github.com/eclipsesource/theia-cloud/commit/46e6fef84a40811249fc67387347284cef56a0f6
