### ISSUE TITLE
NPE in TheiaCloudIngressUtil for AppDefinition without spec

### ISSUE THREAD

**Issue by lucas-koehler** [eclipsesource/theia-cloud#114]
If the `AppDefinition` given to `TheiaCloudIngressUtil.checkForExistingIngressAndAddOwnerReferencesIfMissing` does not have a spec, the method throws a NPE. However, this is a completely incorrect `AppDefinition` then.
We should potentially handle such cases in a more general way than on util method level

**Comment by jfaltermeier** [comment]
Keep open

**Comment by jfaltermeier** [comment]
Keep open
