### ISSUE TITLE
Remove session ingress creation from Operator

### ISSUE THREAD

**Issue by jfaltermeier** [eclipsesource/theia-cloud#117]
If no ingress for instances is existing the operator may create an ingress using `src/main/resources/templateIngress.yaml` as a template. 
In practice we install and adjust the instances ingress via helm. 
We should remove this from the operator as it is not used by default and lacks required flexibility.

**Comment by lucas-koehler** [comment]
@jfaltermeier I renamed the ticket to better reflect the complete removal of the functionality.
