### ISSUE TITLE
Landing page and Try Now page only work with trailing `/` for paths

### ISSUE THREAD

**Issue by lucas-koehler** [eclipsesource/theia-cloud#124]
When using a path based deployment, the landing page and the try now page only work when the url ends with a trailing `/`.

Despite them using different tech stacks (Vue vs React with CRA), the issue seems to be the same:
In order to get them to work on any path without rebuilding the image, they use relative paths to point to resources (e.g. from index.html to the bundle.js).
It seems that without the trailing slash, the base url for the relative paths does not contain the last path segment.
This might be solvable by adjusting the ingress rewrite rules to always append a missing `/`. It needs to be investigated how this can be done properly.

**Comment by sgraband** [comment]
Maybe a topic that could be investigated alongside this is that currently for the `appDef` parameter of the try now page is actually case-sensitive. So for example `https://try.theia-cloud.io/?appDef=coffee-editor` will work, while `https://try.theia-cloud.io/?appdef=coffee-editor` will not work.

While this is not a huge issue, we could still investigate alongside the above mentioned issue to make the urls more robust.
