### ISSUE TITLE
Error on operator-deployment pod

### ISSUE THREAD

**Issue by haminlee** [eclipsesource/theia-cloud#135]
I installed theia-cloud on Azure Kubernetes Service after keycloak done configured successfully.

However, the operator deployment pod was not successfully running with CrashLoopBackOff status.
The web browser of use can see the NGNIX not found error.
The log says there was "unknown options" but not able to progress the further analysis.

Here is the log detail from the pod:

$kubectl logs --tail=100 operator-deployment-bf5b7b756-4fptx
Exception in thread "main" picocli.CommandLine$UnmatchedArgumentException: Unknown options: '--wondershaperImage', 'theiacloud/theia-cloud-wondershaper:0.8.0.MS7'
at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13248)
at picocli.CommandLine$Interpreter.parse(CommandLine.java:13200)
at picocli.CommandLine$Interpreter.parse(CommandLine.java:13146)
at picocli.CommandLine$Interpreter.parse(CommandLine.java:13047)
at picocli.CommandLine.parseArgs(CommandLine.java:1478)
at org.eclipse.theia.cloud.operator.Main.createArguments(Main.java:56)
at org.eclipse.theia.cloud.operator.Main.runMain(Main.java:42)
at org.eclipse.theia.cloud.operator.Main.main(Main.java:38)

Also, the pod shows below:
$ kubectl describe pod operator-deployment-bf5b7b756-4fptx 
Name:             operator-deployment-bf5b7b756-4fptx
Namespace:        theiacloud
Priority:         0
Service Account:  operator-api-service-account
Node:             aks-agentpool-13934957-vmss00000a/[10.224.0.5](https://urldefense.com/v3/__http:/10.224.0.5__;!!AKgNyAfk550h-spHnEo!d6LjQD94lx-zH49ViJr5jrQDGI1xhxmm_UKDu_iq0fMweXbn9SrH31lxifoL5tqEc-76YaPfbppEySCN4rJSHw$)
Start Time:       Wed, 11 Jan 2023 21:30:15 -0800
Labels:           app=operator
                  pod-template-hash=bf5b7b756
Annotations:      <none>
Status:           Running
IP:               10.244.1.7
IPs:
  IP:           10.244.1.7
Controlled By:  ReplicaSet/operator-deployment-bf5b7b756
Containers:
  operator-container:
    Container ID:  containerd://0a1513ba40f44ef65a05f28e9b4caf40d78458e3b784a3f84f18755efedf82d3
    Image:         theiacloud/theia-cloud-operator:0.8.0.MS7
    Image ID:      [docker.io/theiacloud/theia-cloud-operator@sha256:eaf05890d41632c7490bd860e3d2d0a4d14d6656f9d7914a89c92c2a974e1d60](https://urldefense.com/v3/__http:/docker.io/theiacloud/theia-cloud-operator@sha256:eaf05890d41632c7490bd860e3d2d0a4d14d6656f9d7914a89c92c2a974e1d60__;!!AKgNyAfk550h-spHnEo!d6LjQD94lx-zH49ViJr5jrQDGI1xhxmm_UKDu_iq0fMweXbn9SrH31lxifoL5tqEc-76YaPfbppEySBFnMetng$)
    Port:          <none>
    Host Port:     <none>
    Args:
      --keycloak
      --cloudProvider
      K8S
      --bandwidthLimiter
      K8SANNOTATION
      --wondershaperImage
      theiacloud/theia-cloud-wondershaper:0.8.0.MS7
      --serviceUrl
      [https://service.cloud.masftest.com](https://urldefense.com/v3/__https:/service.cloud.masftest.com__;!!AKgNyAfk550h-spHnEo!d6LjQD94lx-zH49ViJr5jrQDGI1xhxmm_UKDu_iq0fMweXbn9SrH31lxifoL5tqEc-76YaPfbppEySA_xtsCBQ$)
      --sessionsPerUser
      1
      --appId
      asdfghjkl
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 11 Jan 2023 21:51:01 -0800
      Finished:     Wed, 11 Jan 2023 21:51:01 -0800
    Ready:          False
    Restart Count:  9
    Environment:    <none>
    Mounts:
      /var/run/secrets/[kubernetes.io/serviceaccount](https://urldefense.com/v3/__http:/kubernetes.io/serviceaccount__;!!AKgNyAfk550h-spHnEo!d6LjQD94lx-zH49ViJr5jrQDGI1xhxmm_UKDu_iq0fMweXbn9SrH31lxifoL5tqEc-76YaPfbppEySBuvLOlRQ$) from kube-api-access-gth2w (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-gth2w:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 [node.kubernetes.io/not-ready:NoExecute](https://urldefense.com/v3/__http:/node.kubernetes.io/not-ready:NoExecute__;!!AKgNyAfk550h-spHnEo!d6LjQD94lx-zH49ViJr5jrQDGI1xhxmm_UKDu_iq0fMweXbn9SrH31lxifoL5tqEc-76YaPfbppEySCoc6aiqA$) op=Exists for 300s
                             [node.kubernetes.io/unreachable:NoExecute](https://urldefense.com/v3/__http:/node.kubernetes.io/unreachable:NoExecute__;!!AKgNyAfk550h-spHnEo!d6LjQD94lx-zH49ViJr5jrQDGI1xhxmm_UKDu_iq0fMweXbn9SrH31lxifoL5tqEc-76YaPfbppEySCjY2XgAw$) op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  24m                   default-scheduler  Successfully assigned theiacloud/operator-deployment-bf5b7b756-4fptx to aks-agentpool-13934957-vmss00000a
  Normal   Pulling    24m                   kubelet            Pulling image "theiacloud/theia-cloud-operator:0.8.0.MS7"
  Normal   Pulled     24m                   kubelet            Successfully pulled image "theiacloud/theia-cloud-operator:0.8.0.MS7" in 1.048725566s
  Normal   Created    22m (x5 over 24m)     kubelet            Created container operator-container
  Normal   Pulled     22m (x4 over 24m)     kubelet            Container image "theiacloud/theia-cloud-operator:0.8.0.MS7" already present on machine
  Normal   Started    22m (x5 over 24m)     kubelet            Started container operator-container
  Warning  BackOff    4m11s (x96 over 24m)  kubelet            Back-off restarting failed container

**Comment by jfaltermeier** [comment]
Hi, please see this answer: https://github.com/eclipsesource/theia-cloud/issues/132#issuecomment-1362885137
We will fix this kind of errors for the 0.8.0.MS8 images

**Comment by haminlee** [comment]
Thank you! It works!!
