### ISSUE TITLE
AWS installation instructions?

### ISSUE THREAD

**Issue by filipthoen2** [eclipsesource/theia-cloud#136]
Any chance someone has AWS installation instructions available, specifically using AWS EKS (I noticed the 'azure' branch has some additional Azure documentation)?

Thanks,

Filip

**Comment by lucas-koehler** [comment]
Hello @filipthoen2 ,
so far we do not have any AWS EKS specific documentation. I'll likely add some documentation for this in the upcoming 2 to 8 weeks but I can't make any promises.

Generally, I assume that most of the required setup is the same as other clusters. I'd pay special attention to setting up the NginX ingress and the storage configuration (in case you want workspace persistence).
If you want to try it yourself, I'd try installing the prerequisites similar to Azure via Helm charts: https://github.com/eclipsesource/theia-cloud/blob/azure-documentation/doc/docs/platforms/Azure.md#install-prerequisites-on-the-cluster

I hope that helps you getting started,
Lucas

PS: For the future, we also have a board for asking questions ;) https://github.com/eclipsesource/theia-cloud/discussions

**Comment by Shashi0838** [comment]
Hi Guys, 

Any progress on this? i would like to try on aws.

Thanks
