### ISSUE TITLE
Helm chart usePaths doesn't seem to work?

### ISSUE THREAD

**Issue by tomqwpl** [eclipsesource/theia-cloud#143]
I've tried deploying the helm chart with the "usePaths" option set, however the landing page app doesn't seem to work in that case.
Is this know to work?
My environment is a bit complicated (I have to deploy this using argocd) so I may be doing something wrong. 
The symptom I get is that the index.html requests the "config.js" file (it's referenced literally as "config.js"), but then fails to request the js and css files, as they are referenced in the index.html as "/js/something" and "/css/something", but the URLs would need to be "/trynow/js/something" or "/trynow/css/something" for them to work I believe?

**Comment by jfaltermeier** [comment]
Hi, thanks for the report. This could be an issue with one of our two sample pages. At the moment we are testing the paths with the try-now-page: https://github.com/eclipsesource/theia-cloud/blob/main/helm/theia.cloud/valuesTestTrynowPage.yaml
We will check the landing-page as well.
