### ISSUE TITLE
Standardize & apply standard formatting

### ISSUE THREAD

**Issue by askarbozcan** [eclipsesource/theia-cloud#152]
In a lot of places in the code, there's a weird mix of tabs & spaces, causing function bodies not to be indented correctly.

For an example, see [LazySessionHandler.java](https://github.com/eclipsesource/theia-cloud/blob/main/java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/impl/LazySessionHandler.java)

It seems that tab size is assumed to be 8 spaces, but then again in a lot places 4 spaces are used for indentation.

I propose adding a convention for the project's code, and perhaps a code formatter (perhaps as a Maven plugin?)

**Comment by sgraband** [comment]
Keep open

**Comment by jfaltermeier** [comment]
Keep open
