### ISSUE TITLE
Implement unit tests

### ISSUE THREAD

**Issue by koegel** [eclipsesource/theia-cloud#18]

**Comment by jfaltermeier** [comment]
Keep open

**Comment by lucas-koehler** [comment]
Regarding the service, initial setup and a unit test that shows how to test resources in the service is available on this branch already: [feat/basic-authorization](https://github.com/eclipsesource/theia-cloud/tree/feat/basic-authorization)

**Comment by askarbozcan** [comment]
Keep open please, operator really needs unit tests IMO.
