### ISSUE TITLE
Operator in eager start mode fails when parsing service yaml

### ISSUE THREAD

**Issue by paulreuter** [eclipsesource/theia-cloud#193]
### Describe the bug

After starting up an operator in eager-start mode with an appdefinition with minInstances=2 and monitor enabled, there seems to be a problem parsing the service yaml file produced from processing the template replacements.

I have yet to run the operator locally in debug mode, but could the newline after the placeholder-monitor-port be the cause?

### Expected behavior

Operator starts up

### Cluster provider

GKE

### Version

0.8.0-MS10v1

### Additional information

> 12:28:31.721 [main] TRACE org.eclipse.theia.cloud.operator.handler.util.K8sUtil - [init] Loading new Service:
> 
> apiVersion: v1
> kind: Service
> metadata:
>   name: a1-a0db1a01-c350-495a-8e42-8d4e202dd67b-service-my-app
>   labels:
>     app: my-app-1
>   namespace: theiacloud
>   ownerReferences:
>     - apiVersion: theia.cloud/v5beta
>       kind: AppDefinition
>       name: placeholder
>       uid: placeholder
> spec:
>   ports:
>     - name: http
>       port: 8081 
>       protocol: TCP
>       targetPort: web
>     8081
> 
>   selector:
>     app: my-app-1
>   type: ClusterIP

> 
> WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
> 12:28:31.854 [main] ERROR org.eclipse.theia.cloud.operator.TheiaCloudImpl - [init] Error while initializing app definitions watch
> org.yaml.snakeyaml.scanner.ScannerException: while scanning a simple key
>  in 'reader', line 19, column 5:
>         8081
>         ^
> could not find expected ':'
>  in 'reader', line 21, column 3:
>       selector:
>       ^
>         at org.yaml.snakeyaml.scanner.ScannerImpl.stalePossibleSimpleKeys(ScannerImpl.java:484) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.scanner.ScannerImpl.needMoreTokens(ScannerImpl.java:299) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:247) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:602) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:165) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:59) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:45) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:140) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:119) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:221) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:191) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:251) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:193) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:313) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:304) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:288) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:195) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:115) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:146) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:151) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.yaml.snakeyaml.Yaml.load(Yaml.java:429) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at io.fabric8.kubernetes.client.utils.Serialization.unmarshalYaml(Serialization.java:370) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:311) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:267) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:255) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at io.fabric8.kubernetes.client.dsl.base.OperationSupport.unmarshal(OperationSupport.java:738) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at io.fabric8.kubernetes.client.dsl.base.BaseOperation.load(BaseOperation.java:259) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at io.fabric8.kubernetes.client.dsl.base.BaseOperation.load(BaseOperation.java:83) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.eclipse.theia.cloud.operator.handler.util.K8sUtil.loadAndCreateTypeWithOwnerReference(K8sUtil.java:163) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.eclipse.theia.cloud.operator.handler.util.K8sUtil.loadAndCreateServiceWithOwnerReference(K8sUtil.java:125) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.eclipse.theia.cloud.operator.handler.impl.EagerStartAppDefinitionAddedHandler.createAndApplyService(EagerStartAppDefinitionAddedHandler.java:174) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.eclipse.theia.cloud.operator.handler.impl.EagerStartAppDefinitionAddedHandler.appDefinitionAdded(EagerStartAppDefinitionAddedHandler.java:109) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.eclipse.theia.cloud.operator.TheiaCloudImpl.handleAppDefnitionEvent(TheiaCloudImpl.java:153) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.eclipse.theia.cloud.operator.TheiaCloudImpl.initAppDefinition(TheiaCloudImpl.java:134) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
>         at org.eclipse.theia.cloud.operator.TheiaCloudImpl.initAppDefinitionsAndWatchForChanges(TheiaCloudImpl.java:99) [operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.eclipse.theia.cloud.operator.TheiaCloudImpl.start(TheiaCloudImpl.java:90) [operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.eclipse.theia.cloud.operator.Main.runMain(Main.java:51) [operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
>         at org.eclipse.theia.cloud.operator.Main.main(Main.java:39) [operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]

**Comment by lucas-koehler** [comment]
Hi @paulreuter ,
thank you very much for the report!

> I have yet to run the operator locally in debug mode, but could the newline after the placeholder-monitor-port be the cause?

No, this should not be the cause.
Instead, the root of the problem most likely is also in `TheiaCloudServiceUtil#getServiceReplacements(String namespace, AppDefinition appDefinition, int instance)` (similar to #192 ). Here, the `placeholder-monitor-port` is not properly replaced as would have been required with the changes introduced in 36f59b46fa7d6e624a89a9a5e63be24192738404 .

Probably this got overlooked as lazy start is the default mode and, thus, tested more carefully.
We'll have a loot at fixing this.

**Comment by dmm9** [comment]
I am currently facing this error with lazy-mode. `[init] Error while initializing app definitions watch`

- Cluster provider: GKE
- Operator Version: branched from `0.8.1.MS2` with only one change to select custom oauth2-proxy version (see [this discussion](https://github.com/eclipsesource/theia-cloud/discussions/236) for details)

I have searched in the logs and the following exception is being thrown (the complete call stack is at the bottom):
```bash
Failure executing: GET at: https://10.95.240.1/apis/theia.cloud/v8beta/namespaces/theiacloud/appdefinitions. Message: Not Found
```
I think the key would be to discover why the internal api call fails. Would an update of fabric8io kubernetes-client to version 6.x (currently 5.12.2) solve the issue? There is one [commit](https://github.com/fabric8io/kubernetes-client/commit/0ebd164432cc2e1e6856a49ed82d3edcf3b84564#diff-707b35b77f89c083b95f7151bae8eefa6e1f2df7ec1deaa423f8559265b36730) in v6.0.0 which transfoms all the client calls to async, but I don't know if this is related to the error. Let me know if I can give more information from GKE logs or status.

- Cluster provider: GKE
- Operator Version: branched from `0.8.1.MS2` with only one change to select custom oauth2-proxy version (see this question for details: #236)

This is the log of the container. As you see, the container restarts every 5 minutes, always with the same behavior:

![grafik](https://github.com/eclipsesource/theia-cloud/assets/11932352/d67e41ae-9243-4a52-8084-6876a0e20bfd)

And this is the detail of the last exception, prior to terminating the execution:
```bash
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.95.240.1/apis/theia.cloud/v8beta/namespaces/theiacloud/appdefinitions. Message: Not Found.
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:682) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:661) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:612) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:555) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:518) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:502) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.listRequestHelper(BaseOperation.java:133) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:415) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:404) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.list(BaseOperation.java:83) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.theia.cloud.common.k8s.client.ResourceClient.list(ResourceClient.java:82) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.theia.cloud.operator.TheiaCloudImpl.initAppDefinitionsAndWatchForChanges(TheiaCloudImpl.java:102) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.theia.cloud.operator.TheiaCloudImpl.start(TheiaCloudImpl.java:92) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.theia.cloud.operator.Main.startOperatorAsLeader(Main.java:120) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.theia.cloud.operator.Main.onStartLeading(Main.java:100) ~[operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at io.fabric8.kubernetes.client.extended.leaderelection.LeaderCallbacks.onStartLeading(LeaderCallbacks.java:34) [operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at io.fabric8.kubernetes.client.extended.leaderelection.LeaderElector.run(LeaderElector.java:70) [operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.theia.cloud.operator.Main.runMain(Main.java:92) [operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.theia.cloud.operator.Main.main(Main.java:52) [operator-0.8.1-SNAPSHOT-jar-with-dependencies.jar:?]
```

**Comment by lucas-koehler** [comment]
Hi @dmm9 , thanks for the detailed report.
Do you encounter since updating your theia cloud installation or did this happen with a  fresh install.
In the update case, I could imagine that you do not have version `v8beta` of the appdefintion CRD. Could you verify this?

**Comment by sgraband** [comment]
To avoid duplication: The same is currently discussed here: https://github.com/eclipsesource/theia-cloud/discussions/236#discussioncomment-6944750.

**Comment by dmm9** [comment]
The issue is solved with the latest [hotfix](https://github.com/eclipsesource/theia-cloud/commit/30e88c7bf6decbbee4c150ab531d6094424515df) from today, where all the the appdefinitions have been consistently updated.
