### ISSUE TITLE
Best practices for CRD updates

### ISSUE THREAD

**Issue by jfaltermeier** [eclipsesource/theia-cloud#203]
### Is your feature request related to a problem? Please describe.

We need to find the best practices for releasing new CRDs. 

Resources:
https://github.com/helm/community/blob/main/hips/hip-0011.md#upgrading-and-modifying-crds

https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#webhook-conversion

https://github.com/operator-framework/josdk-webhooks#conversion-hooks

https://github.com/operator-framework/josdk-webhooks/tree/main/docs

https://github.com/operator-framework/josdk-webhooks/tree/main/samples/commons

**Reproducer create "old" CRs**

theia-cloud branch osweek23-1
theia-cloud-helm branch osweek23-1
terraform test-configuration 2-01_try-now
kubectl apply -f osweek23/session+workspace/workspace.yaml
kubectl apply -f osweek23/session+workspace/session.yaml

**Updated CRDs and prebuilt images are available here:**
theia-cloud branch osweek23-5
theia-cloud-helm branch osweek23-3

### Describe the solution you'd like

- [ ] How to do this with helm?
- [ ] How to update existing CRs to conform to the new CRD?
- [ ] Anything special required to stop old operators?

### Describe alternatives you've considered

-

**Comment by sgraband** [comment]
Keep open
