### ISSUE TITLE
Store status-like properties of CRs in `status` instead of `spec`

### ISSUE THREAD

**Issue by lucas-koehler** [eclipsesource/theia-cloud#212]
### Is your feature request related to a problem? Please describe.

Currently, we store and update fields of CRs (e.g. Sessions' last activity) in spec fields. They might fit better in status fields.
According to https://stackoverflow.com/a/67199015 and the referenced Kubernetes doc, `spec` describes the target state of the cluster while status describes the current state.

This came up while looking at validation of spec fields.

### Describe the solution you'd like

Investigate our CRDs for `spec` fields that should be `status` fields

### Describe alternatives you've considered

Leave everything as is

**Comment by sgraband** [comment]
Keep open
