### ISSUE TITLE
Page not responding

### ISSUE THREAD

**Issue by DaMarcusSullivan** [eclipsesource/theia-cloud#271]
### Describe the bug

While working on a file, the internet page stopped responding and I lost my work and unable to return to where I was.

### Expected behavior

I would like for the page to continue, where it stopped responding so I can continue my work.

### Cluster provider

github.com

### Version

latest ie 2024

**Comment by jfaltermeier** [comment]
Is this ticket about https://try.theia-cloud.io/ ?
This is a free online demo for Theia where pods will be stopped after 30 minutes.
