### ISSUE TITLE
ERROR: Location.replace: 'https://' is not a valid URL.

### ISSUE THREAD

**Issue by 7ojo** [eclipsesource/theia-cloud#319]
### Describe the bug

It is first time me trying theia-cloud version. Did not launch just got 

"
Oh no, something went wrong! ☹

ERROR: Location.replace: 'https://' is not a valid URL.
"

### Expected behavior

Editor should launch probably?

### Additional information

MacOS + Firefox. Latest stable versions

**Comment by sgraband** [comment]
As described in https://github.com/eclipsesource/theia-cloud/discussions/318, the issue should be resolved. Let us know if you should still have any issues.
