### ISSUE TITLE
Error building landing-page docker image

### ISSUE THREAD

**Issue by iyannsch** [eclipsesource/theia-cloud#340]
### Describe the bug

When building the `landing-page` docker file using the provided Dockerfile (`dockerfiles/landing-page/Dockerfile`), the build process crashes due to `Error: Cannot find module '@rollup/rollup-linux-arm64-musl'`.

Moreover this error message is provided, which does not resolve the error even after removing the file+directory and re-installing the packages.

> Error: Cannot find module @rollup/rollup-linux-arm64-musl. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.

### Expected behavior

I expect a functioning docker image to be built without any problem. The image should be usable for `arm64` but foremost for `amd64` architectures.

### Version

80ffd29ac02b62da7c948c5841c655e0b877f405

### Additional information

The problem occurs on both my local laptop (Apple M3 Pro) as well as on GH runners provisioned by GH themselves. 
The problem is resolved when I add `--platform linux/amd64` to the build command

**Comment by lucas-koehler** [comment]
Thanks for the report!
According to this comment https://github.com/rollup/rollup/issues/5295#issuecomment-1944214800 this might be caused by vite. We in fact use vite for the landing page
