### ISSUE TITLE
Require Keycloak authentication by default in all services

### ISSUE THREAD

**Issue by lucas-koehler** [eclipsesource/theia-cloud#91]
If Keycloak usage is not explicitly disabled, the operator and the service should assume that Keycloak authentication is needed. This prevents accidental permission of anonymous access when not configuring Keycloak.

### Current state:
* Service uses it by default with https://github.com/eclipsesource/theia-cloud/pull/90
* Our default helm `values.yaml` disables keycloak.
* Operator implementation in `TheiaCloudArguments` does not seem to set it to true by default => Operator does not use keycloak by default
* `operator.yaml` only adds —keycloak runtime option if keycloak was enabled in values
* Landing page and Try Now page don't use it by default. Seems okay as these are just the front ends.

**Comment by lucas-koehler** [comment]
keep open

**Comment by jfaltermeier** [comment]
Keep open
