### ISSUE TITLE
Review default workspace persistent volume creation to fit production clusters

### ISSUE THREAD

**Issue by lucas-koehler** [eclipsesource/theia-cloud#92]
# Current Situation
We have two operator cloud provider modes configured in the Helm values via `operator.cloudProvider`.
The acceptable values are `K8S` - which suggests the default - and `GKE` (Google Kubernetes Engine).

These modes differ in creating persistent volume claims for persisted workspaces via subclasses of `PersistentVolumeCreator`.

The default implementation in `DefaultPersistentVolumeCreator` first creates a persistent volume (PV) and then the corresponding persistent volume claim (PVC). Thereby, the PV is created on the cluster node's local filesystem via the `hostPath` property. While this makes sense for Minikube, it is not recommeded to use in production:
> In this exercise, you create a hostPath PersistentVolume. Kubernetes supports hostPath for development and testing on a single-node cluster. A hostPath PersistentVolume uses a file or directory on the Node to emulate network-attached storage.
In a production cluster, you would not use hostPath.

Source: https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/#create-a-persistentvolume

Thus, this is not suitable for production.

The `GKEPersistentVolumeCreator` just creates a PVC of storage class `default`. This is supported by Google and Azure and probably also Amazon.

# Suggestion:
The GKE approach should be the default and we should use this in operator mode `K8S`. In addition, we add an operator mode `Minikube` that is used for testing configuration.

In addition, we introduce a new Helm value `operator.storageClass` that allows to configure the storage class of PVCs. This allows cluster admins to define a new StorageClass to their needs that is then used by the operator to create the persistent storage for workspaces.
With this, we enable cluster admins to customize workspace storage with no code modifications and a relatively small implementation effort in Theia.Cloud.

**Comment by jfaltermeier** [comment]
If a cluster admin needs even more control than `operator.storageClass` we may add more helm values once needed and they still have the option to use/provide a custom `PersistentVolumeCreator`-implementation. 
So I think with the proposed approach we have good defaults while allowing customizations.

**Comment by lucas-koehler** [comment]
keep open

**Comment by lucas-koehler** [comment]
Fixed via https://github.com/eclipsesource/theia-cloud/pull/144 and https://github.com/eclipsesource/theia-cloud-helm/pull/12
